### ISSUE TITLE
Password reset failure

### ISSUE THREAD

**Issue by skx** [skx/dhcp.io#27]
Seems the docker-container doesn't have sendmail installed/configured.

**Comment by skx** [comment]
OK this is an annoying one; in the past this software ran on a host which had /usr/lib/sendmail installed, and we'd just shell out to make it work.

Now we're running in a docker container, and so we need to do something more complex:

* As the system doesn't have my mailserver details configured we'll need to update Config.pm to include a set of SMTP credentials.
* We'll then need to update to use an SMTP client library.

In the past I've used `Net::SMTP::SSL` to route via gmail, so that's probably what I'll choose.  Shouldn't be a huge change, but it'll need a bit of care to test it properly.

**Comment by skx** [comment]
FWIW this is the `docker-compose.yml` file I use to launch the application in production:

```
version: "3"

services:
  dhcp-io:
    restart: always
    image: dhcp.io:3
    ports:
      - 127.0.0.1:2000:2000
    volumes:
      - /srv/dhcp.io/db.db:/root/db.db
      - /srv/dhcp.io/Config.pm:/srv/lib/DHCP/Config.pm:ro
    links:
      - redis:redis
  redis:
    restart: always
    image: redis
```

As you can see we bind-mount the `Config.pm` into place, so that'll need updating for production too.
